# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/chat.proto',
  package='chat',
  syntax='proto3',
  serialized_pb=_b('\n\x13protobuf/chat.proto\x12\x04\x63hat\x1a\x19google/protobuf/any.proto\";\n\x06NetMsg\x12\r\n\x05token\x18\x01 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\")\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"I\n\rLoginResponse\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0c\n\x04info\x18\x04 \x01(\t\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\t\"3\n\rSignupRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"!\n\rLogoutRequest\x12\x10\n\x08senderID\x18\x01 \x01(\x05\"\'\n\x13GetUserInfosRequest\x12\x10\n\x08senderID\x18\x01 \x01(\x05\"5\n\x14GetUserInfosResponse\x12\x1d\n\x05users\x18\x01 \x03(\x0b\x32\x0e.chat.UserInfo\"=\n\x12GetMessagesRequest\x12\x10\n\x08senderID\x18\x01 \x01(\x05\x12\x15\n\rafterTimeUnix\x18\x02 \x01(\x05\":\n\x13GetMessagesResponse\x12#\n\x08messages\x18\x01 \x03(\x0b\x32\x11.chat.ChatMessage\"7\n\x11MakeFriendRequest\x12\x10\n\x08senderID\x18\x01 \x01(\x05\x12\x10\n\x08targetID\x18\x02 \x01(\x05\"n\n\x0b\x43hatMessage\x12\x10\n\x08senderID\x18\x01 \x01(\x05\x12\x10\n\x08targetID\x18\x02 \x01(\x05\x12\x10\n\x08timeUnix\x18\x03 \x01(\x05\x12\x0e\n\x04text\x18\n \x01(\tH\x00\x12\x0e\n\x04\x66ile\x18\x0b \x01(\x0cH\x00\x42\t\n\x07\x43ontent\"L\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08isFriend\x18\n \x01(\x08\x12\x10\n\x08isOnline\x18\x0b \x01(\x08\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_NETMSG = _descriptor.Descriptor(
  name='NetMsg',
  full_name='chat.NetMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='chat.NetMsg.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='chat.NetMsg.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=115,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='chat.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='chat.Response.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='chat.Response.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=158,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='chat.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='chat.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='chat.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=210,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='chat.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='chat.LoginResponse.success', index=0,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='chat.LoginResponse.info', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='chat.LoginResponse.id', index=2,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='chat.LoginResponse.token', index=3,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=285,
)


_SIGNUPREQUEST = _descriptor.Descriptor(
  name='SignupRequest',
  full_name='chat.SignupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='chat.SignupRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='chat.SignupRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=338,
)


_LOGOUTREQUEST = _descriptor.Descriptor(
  name='LogoutRequest',
  full_name='chat.LogoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderID', full_name='chat.LogoutRequest.senderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=373,
)


_GETUSERINFOSREQUEST = _descriptor.Descriptor(
  name='GetUserInfosRequest',
  full_name='chat.GetUserInfosRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderID', full_name='chat.GetUserInfosRequest.senderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=414,
)


_GETUSERINFOSRESPONSE = _descriptor.Descriptor(
  name='GetUserInfosResponse',
  full_name='chat.GetUserInfosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='users', full_name='chat.GetUserInfosResponse.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=469,
)


_GETMESSAGESREQUEST = _descriptor.Descriptor(
  name='GetMessagesRequest',
  full_name='chat.GetMessagesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderID', full_name='chat.GetMessagesRequest.senderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='afterTimeUnix', full_name='chat.GetMessagesRequest.afterTimeUnix', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=532,
)


_GETMESSAGESRESPONSE = _descriptor.Descriptor(
  name='GetMessagesResponse',
  full_name='chat.GetMessagesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='chat.GetMessagesResponse.messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=592,
)


_MAKEFRIENDREQUEST = _descriptor.Descriptor(
  name='MakeFriendRequest',
  full_name='chat.MakeFriendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderID', full_name='chat.MakeFriendRequest.senderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetID', full_name='chat.MakeFriendRequest.targetID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=594,
  serialized_end=649,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='chat.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderID', full_name='chat.ChatMessage.senderID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetID', full_name='chat.ChatMessage.targetID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeUnix', full_name='chat.ChatMessage.timeUnix', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='chat.ChatMessage.text', index=3,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='chat.ChatMessage.file', index=4,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Content', full_name='chat.ChatMessage.Content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=651,
  serialized_end=761,
)


_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='chat.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chat.UserInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='chat.UserInfo.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isFriend', full_name='chat.UserInfo.isFriend', index=2,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isOnline', full_name='chat.UserInfo.isOnline', index=3,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=763,
  serialized_end=839,
)

_NETMSG.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_GETUSERINFOSRESPONSE.fields_by_name['users'].message_type = _USERINFO
_GETMESSAGESRESPONSE.fields_by_name['messages'].message_type = _CHATMESSAGE
_CHATMESSAGE.oneofs_by_name['Content'].fields.append(
  _CHATMESSAGE.fields_by_name['text'])
_CHATMESSAGE.fields_by_name['text'].containing_oneof = _CHATMESSAGE.oneofs_by_name['Content']
_CHATMESSAGE.oneofs_by_name['Content'].fields.append(
  _CHATMESSAGE.fields_by_name['file'])
_CHATMESSAGE.fields_by_name['file'].containing_oneof = _CHATMESSAGE.oneofs_by_name['Content']
DESCRIPTOR.message_types_by_name['NetMsg'] = _NETMSG
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['SignupRequest'] = _SIGNUPREQUEST
DESCRIPTOR.message_types_by_name['LogoutRequest'] = _LOGOUTREQUEST
DESCRIPTOR.message_types_by_name['GetUserInfosRequest'] = _GETUSERINFOSREQUEST
DESCRIPTOR.message_types_by_name['GetUserInfosResponse'] = _GETUSERINFOSRESPONSE
DESCRIPTOR.message_types_by_name['GetMessagesRequest'] = _GETMESSAGESREQUEST
DESCRIPTOR.message_types_by_name['GetMessagesResponse'] = _GETMESSAGESRESPONSE
DESCRIPTOR.message_types_by_name['MakeFriendRequest'] = _MAKEFRIENDREQUEST
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetMsg = _reflection.GeneratedProtocolMessageType('NetMsg', (_message.Message,), dict(
  DESCRIPTOR = _NETMSG,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.NetMsg)
  ))
_sym_db.RegisterMessage(NetMsg)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Response)
  ))
_sym_db.RegisterMessage(Response)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSE,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LoginResponse)
  ))
_sym_db.RegisterMessage(LoginResponse)

SignupRequest = _reflection.GeneratedProtocolMessageType('SignupRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPREQUEST,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.SignupRequest)
  ))
_sym_db.RegisterMessage(SignupRequest)

LogoutRequest = _reflection.GeneratedProtocolMessageType('LogoutRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTREQUEST,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LogoutRequest)
  ))
_sym_db.RegisterMessage(LogoutRequest)

GetUserInfosRequest = _reflection.GeneratedProtocolMessageType('GetUserInfosRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERINFOSREQUEST,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.GetUserInfosRequest)
  ))
_sym_db.RegisterMessage(GetUserInfosRequest)

GetUserInfosResponse = _reflection.GeneratedProtocolMessageType('GetUserInfosResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERINFOSRESPONSE,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.GetUserInfosResponse)
  ))
_sym_db.RegisterMessage(GetUserInfosResponse)

GetMessagesRequest = _reflection.GeneratedProtocolMessageType('GetMessagesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMESSAGESREQUEST,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.GetMessagesRequest)
  ))
_sym_db.RegisterMessage(GetMessagesRequest)

GetMessagesResponse = _reflection.GeneratedProtocolMessageType('GetMessagesResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETMESSAGESRESPONSE,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.GetMessagesResponse)
  ))
_sym_db.RegisterMessage(GetMessagesResponse)

MakeFriendRequest = _reflection.GeneratedProtocolMessageType('MakeFriendRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAKEFRIENDREQUEST,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.MakeFriendRequest)
  ))
_sym_db.RegisterMessage(MakeFriendRequest)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), dict(
  DESCRIPTOR = _CHATMESSAGE,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatMessage)
  ))
_sym_db.RegisterMessage(ChatMessage)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), dict(
  DESCRIPTOR = _USERINFO,
  __module__ = 'protobuf.chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.UserInfo)
  ))
_sym_db.RegisterMessage(UserInfo)


# @@protoc_insertion_point(module_scope)
